---
# Play to test ping on Applications servers
- name: Ping EBS Applications servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping app servers
      ping:
      register: ping_output
    
    - name: Show output
      debug: 
        msg: "{{ ping_output.ping }}"
  become: true
